server:
  port: 8300

eureka:
 client:
   healthcheck:
     enabled: true
   service-url:
     defaultZone: http://libo:libo@erk-node1:9000/eureka,http://libo:libo@erk-node2:9001/eureka
 instance:
   prefer-ip-address: true
spring:
  application:
    name: microservice-admin

security:
  basic:
    enabled: false